I'm echoing to stdout
I'm echoing to stderr
My JobID is 55699319
I have 4 CPUs on node r108u25n01
Using backend: pytorch
cuda not available
[I] Loading dataset ZINC...
WARNING:root:The OGB package is out of date. Your version is 1.2.3, while the latest version is 1.3.6.
train, test, val sizes : 10000 1000 1000
[I] Finished loading.
[I] Data load time: 5.3987s
MODEL DETAILS:

MODEL/Total parameters: MLP 108975
Training Graphs:  10000
Validation Graphs:  1000
Test Graphs:  1000
  0%|          | 0/1000 [00:00<?, ?it/s]Epoch 0:   0%|          | 0/1000 [00:00<?, ?it/s]Epoch 0:   0%|          | 0/1000 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/vast/palmer/pi/krishnaswamy_smita/bsw38/GraphML/benchmarking-gnns/train/train_molecules_graph_regression.py", line 27, in train_epoch_sparse
    batch_pos_enc = batch_graphs.ndata['pos_enc'].to(device)
  File "/home/bsw38/.conda/envs/benchmark_gnn/lib/python3.7/site-packages/dgl/view.py", line 66, in __getitem__
    return self._graph._get_n_repr(self._ntid, self._nodes)[key]
  File "/home/bsw38/.conda/envs/benchmark_gnn/lib/python3.7/site-packages/dgl/frame.py", line 386, in __getitem__
    return self._columns[name].data
KeyError: 'pos_enc'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main_molecules_graph_regression.py", line 439, in <module>
    main()    
  File "main_molecules_graph_regression.py", line 430, in main
    train_val_pipeline(MODEL_NAME, dataset, params, net_params, dirs)
  File "main_molecules_graph_regression.py", line 176, in train_val_pipeline
    epoch_train_loss, epoch_train_mae, optimizer = train_epoch(model, optimizer, device, train_loader, epoch)
  File "/vast/palmer/pi/krishnaswamy_smita/bsw38/GraphML/benchmarking-gnns/train/train_molecules_graph_regression.py", line 33, in train_epoch_sparse
    batch_scores = model.forward(batch_graphs, batch_x, batch_e)
  File "/vast/palmer/pi/krishnaswamy_smita/bsw38/GraphML/benchmarking-gnns/nets/molecules_graph_regression/mlp_net.py", line 119, in forward
    h = self._to_spectral(g, h)
  File "/vast/palmer/pi/krishnaswamy_smita/bsw38/GraphML/benchmarking-gnns/nets/molecules_graph_regression/mlp_net.py", line 95, in _to_spectral
    eigs = MLPNet._get_eigenvectors(induced) # nxk
  File "/vast/palmer/pi/krishnaswamy_smita/bsw38/GraphML/benchmarking-gnns/nets/molecules_graph_regression/mlp_net.py", line 78, in _get_eigenvectors
    torch_eigenvectors = torch.randn(num_nodes, self.num_eigenvectors, device=torch_eigenvectors.device)
NameError: name 'num_nodes' is not defined
